etcd:
  image: quay.io/coreos/etcd:v2.2.4
  command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
rust:
  image: jimmycuadra/rust
  environment:
    RUST_BACKTRACE: 1
    RUST_TEST_THREADS: 1
  links:
    - etcd
  volumes:
    - .:/source
