version: "2"
services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.8
    command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
  etcdsecure:
    image: quay.io/coreos/etcd:v2.3.8
    command: -advertise-client-urls=https://0.0.0.0:2379 -listen-client-urls=https://0.0.0.0:2379 -trusted-ca-file=/ssl/ca.pem -cert-file=/ssl/server.pem -key-file=/ssl/server-key.pem -client-cert-auth
    volumes:
      - ./tests/ssl:/ssl
  rust:
    image: rust:1.31.0
    environment:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    links:
      - etcd
      - etcdsecure
    working_dir: /source
    volumes:
      - .:/source
      - cargo_git:/root/.cargo/git
      - cargo_registry:/root/.cargo/registry
volumes:
  cargo_git: {}
  cargo_registry: {}
